id: P000742
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W19960
  title: རྟགས་ཀྱི་འཇུག་པའི་དཀའ་འགྲེལ་གནད་ཀྱི་སྒྲོན་མེ།
  author: ''
  volumes:
    c5f098bc2d684cc9a587c591b0639ffb:
      image_group_id: I4737
      title: ''
      volume_number: 1
      total_pages: 152
      base_file: v001.txt
