id: P000742
initial_creation_type: ocr
source_metadata:
  id: bdr:W19960
  title: རྟགས་ཀྱི་འཇུག་པའི་དཀའ་འགྲེལ་གནད་ཀྱི་སྒྲོན་མེ།
  author: ''
  volumes:
    c5f098bc2d684cc9a587c591b0639ffb:
      image_group_id: I4737
      title: ''
      volume_number: 1
      total_pages: 152
