id: IEF293934
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T09:53:34+00:00'
last_modified: '2022-06-07T13:36:44.794343+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19960
  title: རྟགས་ཀྱི་འཇུག་པའི་དཀའ་འགྲེལ་གནད་ཀྱི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D3C1:
      image_group_id: I4737
      title: ''
      total_pages: 152
      order: 1
      base_file: D3C1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
